# Generated by Django 4.1.7 on 2023-03-27 15:15

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('track_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.CharField(max_length=20),
        ),
    ]
